[package]
name = "git-release-name-web"
version = "0.1.0"
authors = ["Kevin Choubacha <chewbacha@gmail.com>"]

[dependencies]
git-release-name = { path = "../dictionary" }
actix-web = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
rand = "0.5"
